---
title: "Text Analytics Using Quanteda"
author: "Monica Campos"
---

a\. Biden-Xi summit data

The analysis of the Biden-Xi Summit Twitter data, discusses the meeting between the two presidents at the November 2021 summit, contained 14,220 rows, 90 columns. The text analysis was made using the Algorithmic Modeling Culture for pattern discovery using R tools of quanteda and ggplot2 to demonstrate nd plot the process of turning noisy social media data into quantifiable structure to draw insights on nature of conversation.

There are three key findings that provide structural connectivity in a heavy political discussion:

\(1\) The corpus had 58,080 documents or tweets and 63, 972 features or unique words, which explains the following the needed dimension reduction that was successfully completed by Latent Semantic Analysis (LSA). The LSA reduced the complexity to four latent dimensions/topics. This means the Biden-Xi Summit can be summarized in four underlying themes.

\(2\) The second finding is the Feature Co-occurrence Matrix (FCM) of the hashtags that were used to revealed a strong, quantifiable relationship between entities. The highest co-occurrence of 443 times was between #biden and #china. Similarly, the hashtags between country and leader: #china and #xijinping had a strong linkage.

\(3\) Influence and User Context: The three official accounts (\@potus and \@joebiden), and major media and news sources (\@politico, \@nytimes) are identified as the top entities in the conversation. The final piece of the code was the creation of a matrix (user_fm) to map which users were mentioned together to draw insights and understanding on the flow of political discourse.

b\. US presidential inaugural speeches

This code analyzes the United States Presidential Inaugural Speeches using a variety of techniques (word clouds, KWIC/X-Ray Plots, frequency measures, and Keyness analysis) to track rhetorical changes over time and stylistic differences between leaders.

i.  Any similarities and differences over time and among presidents?

Presidents became less likely to refer to the country as the "Union" and less likely to mention "Constitution" or "Foreign" countries. As time passed they were more likely to refer to the United States as "America" and more likely to mention "freedom" and "God."

c\. What is Wordfish? 

Based on the quanteda website, Wordfish is an unsupervised scaling model used to estimate the relative ideological or policy positions of texts/documents with a single, latent dimensions. Also, it is considered a Poisson scaling model that uses the maximum likelihood estimation to simultaneously determine both the estimated positions of the document and words (features) within the text. Wordfish does not require any assignment of policy position or reference scores. The only thing it needs is to set the orientation and document of the scale using two specific documents (e.g. dir = c(6,5))).

Learn more about WordFish: <https://quanteda.io/articles/pkgdown/examples/plotting.html?q=wordfish#wordfish>)
